Первоначальная версия readme
Telepuziki/To-do-List pull request #9
Opened 2023-11-28 07:40 UTC by smartis2816

2023-11-28 07:54 UTC, DenisYakunin commented
Мне понравилось. Нужно исправить опечатку с буллет поинтом и думаю можно выгружать.

2023-11-28 08:11 UTC, smartis2816 commented
Опечатка с буллет поинтом исправлена.

2023-11-28 08:14 UTC, DenisYakunin approved these changes

2023-11-28 08:15 UTC, Darina1801 commented on README.md
> +- [ ] Лого продукта
Лого продукта уже есть, так что можно тоже пометить

2023-11-28 08:19 UTC, Darina1801 requested changes

2023-11-28 08:19 UTC, Darina1801 commented on README.md
> +- [ ] Закончить README проекта
Это тоже можно отметить

2023-11-28 08:19 UTC, Darina1801 commented on README.md
> +Представляем вам приложение для составления списка дел, .
Я вижу ", .", давай оставим один знак препинания

2023-11-28 08:19 UTC, Darina1801 commented on README.md
> +    <img src="https://private-user-images.githubusercontent.com/138122117/283590987-182a79f2-73fe-4c73-b6b6-0d3f9b0f3386.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkI
Может добавим эту картинку в папку в коде и будем вызывать оттуда?

2023-12-05 07:44 UTC, smartis2816 commented
Создан новый коммит с изменениями в соответствии с предложениями Дарины:
- исправлена опечатка;
- логотип заменён на логотип приложения, а не команды, и загружается из папки проекта;
- подправлен roadmap.

2023-12-05 18:42 UTC, Darina1801 approved these changes

2023-12-05 18:43 UTC, merged